# =============================================================================
# media-vm - Swap Configuration
# =============================================================================

swap_file_path: /swap.img
swap_size_gb: 16
