# =============================================================================
# pve-alto - Proxmox Guest Hardware Settings
# =============================================================================

proxmox_vm_hardware:
  - name: pdm-vm
    vmid: 150
    cores: 2
    memory: 2048
