services:
  profilarr:
    image: ghcr.io/dictionarry-hub/profilarr:latest
    container_name: profilarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - ORIGIN=https://profilarr.jnalley.me
      - PARSER_HOST=profilarr-parser
      - PARSER_PORT=5000
    volumes:
      - ./config:/config
    ports:
      - "6868:6868"
    depends_on:
      profilarr-parser:
        condition: service_healthy
    restart: unless-stopped

  profilarr-parser:
    image: ghcr.io/dictionarry-hub/profilarr-parser:latest
    container_name: profilarr-parser
    expose:
      - "5000"
    restart: unless-stopped
