#!/usr/bin/env python3
"""Receive bounded Health Auto Export JSON and store normalized SQLite rows.

This process is intentionally independent from OpenClaw. The model-facing
runtime receives only aggregate reports generated by ``health-summary.py``.
"""

import hashlib
import hmac
import ipaddress
import json
import math
import os
import sqlite3
import sys
import time
from collections import defaultdict, deque
from datetime import datetime
from http.server import HTTPServer, BaseHTTPRequestHandler
from threading import Lock


def load_secret(env_name: str, file_env_name: str) -> str:
    secret_path = os.environ.get(file_env_name, "").strip()
    if secret_path:
        try:
            with open(secret_path, encoding="utf-8") as secret_file:
                return secret_file.read().strip()
        except OSError as exc:
            raise RuntimeError(f"Unable to read {file_env_name}") from exc
    return os.environ.get(env_name, "").strip()


PORT = int(os.environ.get("HEALTH_RECEIVER_PORT", "18791"))
TOKEN = load_secret("HEALTH_RECEIVER_TOKEN", "HEALTH_RECEIVER_TOKEN_FILE")
BIND_ADDR = os.environ.get("HEALTH_RECEIVER_BIND", "127.0.0.1")
ALLOWED_SOURCES = {
    value.strip()
    for value in os.environ.get("HEALTH_RECEIVER_ALLOWED_SOURCES", "127.0.0.1").split(
        ","
    )
    if value.strip()
}
MAX_BODY_BYTES = int(os.environ.get("HEALTH_RECEIVER_MAX_BODY_BYTES", "16777216"))
RATE_LIMIT = int(os.environ.get("HEALTH_RECEIVER_RATE_LIMIT", "30"))
RATE_WINDOW_SECONDS = int(os.environ.get("HEALTH_RECEIVER_RATE_WINDOW_SECONDS", "60"))
MAX_JSON_DEPTH = int(os.environ.get("HEALTH_RECEIVER_MAX_JSON_DEPTH", "16"))
MAX_JSON_NODES = int(os.environ.get("HEALTH_RECEIVER_MAX_JSON_NODES", "1000000"))
MAX_COLLECTION_ITEMS = int(
    os.environ.get("HEALTH_RECEIVER_MAX_COLLECTION_ITEMS", "200000")
)
MAX_STRING_BYTES = int(os.environ.get("HEALTH_RECEIVER_MAX_STRING_BYTES", "1048576"))
DB_PATH = os.environ.get("HEALTH_DB_PATH", "/var/lib/openclaw-health/health.db")
REQUEST_TIMES = defaultdict(deque)
REQUEST_TIMES_LOCK = Lock()


class PayloadError(ValueError):
    """Raised when a request is valid JSON but outside the accepted schema."""


def reject_nonstandard_number(value: str):
    raise PayloadError(f"Non-standard JSON number is not accepted: {value}")


def validate_json_shape(value):
    """Bound recursive structure before any database work begins."""
    stack = [(value, 0)]
    nodes = 0

    while stack:
        item, depth = stack.pop()
        nodes += 1
        if nodes > MAX_JSON_NODES:
            raise PayloadError("JSON body contains too many values")
        if depth > MAX_JSON_DEPTH:
            raise PayloadError("JSON body is nested too deeply")

        if isinstance(item, dict):
            if len(item) > MAX_COLLECTION_ITEMS:
                raise PayloadError("JSON object contains too many fields")
            for key, child in item.items():
                if len(key.encode("utf-8")) > MAX_STRING_BYTES:
                    raise PayloadError("JSON field name is too large")
                stack.append((child, depth + 1))
        elif isinstance(item, list):
            if len(item) > MAX_COLLECTION_ITEMS:
                raise PayloadError("JSON array contains too many items")
            stack.extend((child, depth + 1) for child in item)
        elif isinstance(item, str):
            if len(item.encode("utf-8")) > MAX_STRING_BYTES:
                raise PayloadError("JSON string is too large")


def require_object(value, context: str):
    if not isinstance(value, dict):
        raise PayloadError(f"{context} must be an object")
    return value


def require_array(value, context: str):
    if not isinstance(value, list):
        raise PayloadError(f"{context} must be an array")
    return value


def finite_number(value, context: str, default=None):
    if value is None:
        return default
    if isinstance(value, dict):
        value = value.get("qty", value.get("value"))
    if value is None:
        return default
    if isinstance(value, bool):
        raise PayloadError(f"{context} must be numeric")
    try:
        number = float(value)
    except (TypeError, ValueError) as exc:
        raise PayloadError(f"{context} must be numeric") from exc
    if not math.isfinite(number):
        raise PayloadError(f"{context} must be finite")
    return number


def text_value(value, context: str, default: str = "", max_bytes: int = 512):
    if value is None:
        return default
    if not isinstance(value, (str, int, float)) or isinstance(value, bool):
        raise PayloadError(f"{context} must be text")
    text = str(value)
    if len(text.encode("utf-8")) > max_bytes:
        raise PayloadError(f"{context} is too large")
    return text


def compact_json(value) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def init_db():
    """Create the database and tables if they don't exist."""
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    # Main metrics table - stores individual data points
    c.execute("""
        CREATE TABLE IF NOT EXISTS health_metrics (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            metric_name TEXT NOT NULL,
            value REAL,
            unit TEXT,
            date_start TEXT,
            date_end TEXT,
            source TEXT,
            received_at TEXT DEFAULT (datetime('now')),
            raw_json TEXT,
            row_hash TEXT
        )
    """)

    # Workouts table
    c.execute("""
        CREATE TABLE IF NOT EXISTS workouts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            workout_type TEXT,
            duration_minutes REAL,
            calories REAL,
            distance REAL,
            distance_unit TEXT,
            date_start TEXT,
            date_end TEXT,
            source TEXT,
            received_at TEXT DEFAULT (datetime('now')),
            raw_json TEXT,
            row_hash TEXT
        )
    """)

    # Sleep table - separate for easier querying
    c.execute("""
        CREATE TABLE IF NOT EXISTS sleep (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            sleep_state TEXT,
            date_start TEXT,
            date_end TEXT,
            duration_minutes REAL,
            source TEXT,
            received_at TEXT DEFAULT (datetime('now')),
            raw_json TEXT,
            row_hash TEXT
        )
    """)

    # Compatibility migration for existing databases created before row hashes.
    for table in ("health_metrics", "workouts", "sleep"):
        columns = {row[1] for row in c.execute(f"PRAGMA table_info({table})")}
        if "row_hash" not in columns:
            c.execute(f"ALTER TABLE {table} ADD COLUMN row_hash TEXT")

    # Index for fast date-range queries and duplicate prevention.
    c.execute(
        "CREATE INDEX IF NOT EXISTS idx_metrics_name_date ON health_metrics(metric_name, date_start)"
    )
    c.execute("CREATE INDEX IF NOT EXISTS idx_workouts_date ON workouts(date_start)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_sleep_date ON sleep(date_start)")
    c.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_metrics_row_hash ON health_metrics(row_hash) WHERE row_hash IS NOT NULL"
    )
    c.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_workouts_row_hash ON workouts(row_hash) WHERE row_hash IS NOT NULL"
    )
    c.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_sleep_row_hash ON sleep(row_hash) WHERE row_hash IS NOT NULL"
    )

    conn.commit()
    conn.close()
    print(f"Database ready at {DB_PATH}")


def row_hash(*values):
    """Stable hash for duplicate Health Auto Export samples."""
    payload = json.dumps(
        values, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def insert_count(cursor, sql, values):
    before = cursor.connection.total_changes
    cursor.execute(sql, values)
    return 1 if cursor.connection.total_changes > before else 0


def store_metrics(data):
    """Parse and atomically store recognized Health Auto Export records."""
    validate_json_shape(data)
    payload = data.get("data", data) if isinstance(data, dict) else data
    if not isinstance(payload, (dict, list)):
        raise PayloadError("data must be an object or array")

    counts = {"metrics": 0, "workouts": 0, "sleep": 0}
    conn = sqlite3.connect(DB_PATH, timeout=30)
    cursor = conn.cursor()

    try:
        if isinstance(payload, dict) and "metrics" in payload:
            for metric_index, metric_value in enumerate(
                require_array(payload["metrics"], "metrics")
            ):
                metric = require_object(metric_value, f"metrics[{metric_index}]")
                name = text_value(
                    metric.get("name", metric.get("type", "unknown")),
                    f"metrics[{metric_index}].name",
                    max_bytes=256,
                )
                units = text_value(
                    metric.get("units", metric.get("unit", "")),
                    f"metrics[{metric_index}].units",
                    max_bytes=64,
                )
                points = require_array(
                    metric.get("data", []), f"metrics[{metric_index}].data"
                )

                for point_index, point_value in enumerate(points):
                    point = require_object(
                        point_value,
                        f"metrics[{metric_index}].data[{point_index}]",
                    )
                    raw_value = point.get("qty", point.get("value", point.get("avg")))
                    if raw_value is None:
                        continue
                    value = finite_number(
                        raw_value,
                        f"metrics[{metric_index}].data[{point_index}].value",
                    )
                    date_start = text_value(
                        point.get("date", point.get("startDate", "")),
                        "metric date_start",
                        max_bytes=128,
                    )
                    date_end = text_value(
                        point.get("endDate", point.get("date", "")),
                        "metric date_end",
                        max_bytes=128,
                    )
                    source = text_value(
                        point.get("source", ""), "metric source", max_bytes=512
                    )
                    counts["metrics"] += insert_count(
                        cursor,
                        """
                        INSERT OR IGNORE INTO health_metrics
                            (metric_name, value, unit, date_start, date_end,
                             source, raw_json, row_hash)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                        (
                            name,
                            value,
                            units,
                            date_start,
                            date_end,
                            source,
                            compact_json(point),
                            row_hash(
                                name,
                                value,
                                units,
                                date_start,
                                date_end,
                                source,
                            ),
                        ),
                    )

        if isinstance(payload, dict) and "workouts" in payload:
            for index, workout_value in enumerate(
                require_array(payload["workouts"], "workouts")
            ):
                workout = require_object(workout_value, f"workouts[{index}]")
                workout_type = text_value(
                    workout.get("name", workout.get("workoutActivityType", "unknown")),
                    f"workouts[{index}].name",
                    max_bytes=256,
                )
                duration = finite_number(
                    workout.get("duration"), f"workouts[{index}].duration", 0
                )
                calories = finite_number(
                    workout.get("activeEnergy", workout.get("totalEnergyBurned")),
                    f"workouts[{index}].calories",
                    0,
                )
                distance_value = workout.get("distance")
                distance = finite_number(
                    distance_value, f"workouts[{index}].distance", 0
                )
                distance_unit = text_value(
                    (
                        distance_value.get("units", "mi")
                        if isinstance(distance_value, dict)
                        else "mi"
                    ),
                    f"workouts[{index}].distance_unit",
                    max_bytes=64,
                )
                date_start = text_value(
                    workout.get("start", workout.get("startDate", "")),
                    "workout date_start",
                    max_bytes=128,
                )
                date_end = text_value(
                    workout.get("end", workout.get("endDate", "")),
                    "workout date_end",
                    max_bytes=128,
                )
                source = text_value(
                    workout.get("source", ""), "workout source", max_bytes=512
                )
                counts["workouts"] += insert_count(
                    cursor,
                    """
                    INSERT OR IGNORE INTO workouts
                        (workout_type, duration_minutes, calories, distance,
                         distance_unit, date_start, date_end, source, raw_json,
                         row_hash)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        workout_type,
                        duration,
                        calories,
                        distance,
                        distance_unit,
                        date_start,
                        date_end,
                        source,
                        compact_json(workout),
                        row_hash(
                            workout_type,
                            duration,
                            calories,
                            distance,
                            distance_unit,
                            date_start,
                            date_end,
                            source,
                        ),
                    ),
                )

        if isinstance(payload, dict) and "sleep" in payload:
            for index, sleep_value in enumerate(
                require_array(payload["sleep"], "sleep")
            ):
                sleep = require_object(sleep_value, f"sleep[{index}]")
                sleep_state = text_value(
                    sleep.get("state", sleep.get("value", "unknown")),
                    f"sleep[{index}].state",
                    max_bytes=128,
                )
                date_start = text_value(
                    sleep.get("startDate", sleep.get("date", "")),
                    "sleep date_start",
                    max_bytes=128,
                )
                date_end = text_value(
                    sleep.get("endDate", ""), "sleep date_end", max_bytes=128
                )
                duration = finite_number(
                    sleep.get("duration"), f"sleep[{index}].duration", 0
                )
                source = text_value(
                    sleep.get("source", ""), "sleep source", max_bytes=512
                )
                counts["sleep"] += insert_count(
                    cursor,
                    """
                    INSERT OR IGNORE INTO sleep
                        (sleep_state, date_start, date_end, duration_minutes,
                         source, raw_json, row_hash)
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        sleep_state,
                        date_start,
                        date_end,
                        duration,
                        source,
                        compact_json(sleep),
                        row_hash(sleep_state, date_start, date_end, duration, source),
                    ),
                )

        if isinstance(payload, list):
            for index, item_value in enumerate(payload):
                item = require_object(item_value, f"data[{index}]")
                raw_value = item.get("qty", item.get("value", item.get("avg")))
                if raw_value is None:
                    continue
                name = text_value(
                    item.get("name", item.get("type", "unknown")),
                    f"data[{index}].name",
                    max_bytes=256,
                )
                value = finite_number(raw_value, f"data[{index}].value")
                units = text_value(
                    item.get("units", item.get("unit", "")),
                    f"data[{index}].units",
                    max_bytes=64,
                )
                date_start = text_value(
                    item.get("date", item.get("startDate", "")),
                    "metric date_start",
                    max_bytes=128,
                )
                date_end = text_value(
                    item.get("endDate", item.get("date", "")),
                    "metric date_end",
                    max_bytes=128,
                )
                source = text_value(
                    item.get("source", ""), "metric source", max_bytes=512
                )
                counts["metrics"] += insert_count(
                    cursor,
                    """
                    INSERT OR IGNORE INTO health_metrics
                        (metric_name, value, unit, date_start, date_end, source,
                         raw_json, row_hash)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        name,
                        value,
                        units,
                        date_start,
                        date_end,
                        source,
                        compact_json(item),
                        row_hash(name, value, units, date_start, date_end, source),
                    ),
                )

        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()

    return counts


class HealthReceiver(BaseHTTPRequestHandler):
    server_version = "HealthReceiver"
    sys_version = ""

    def send_json(self, status, payload):
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def request_allowed(self):
        source = self.client_address[0]
        if source not in ALLOWED_SOURCES:
            self.send_json(403, {"error": "Forbidden"})
            return False

        now = time.monotonic()
        with REQUEST_TIMES_LOCK:
            requests = REQUEST_TIMES[source]
            while requests and now - requests[0] >= RATE_WINDOW_SECONDS:
                requests.popleft()
            if len(requests) >= RATE_LIMIT:
                self.send_response(429)
                self.send_header("Content-Type", "application/json")
                self.send_header("Retry-After", str(RATE_WINDOW_SECONDS))
                self.end_headers()
                self.wfile.write(b'{"error":"Too Many Requests"}')
                return False
            requests.append(now)

        auth = self.headers.get("Authorization", "")
        bearer = auth[7:] if auth.startswith("Bearer ") else ""
        api_key = self.headers.get("X-API-Key", "")
        if not (
            hmac.compare_digest(bearer, TOKEN) or hmac.compare_digest(api_key, TOKEN)
        ):
            self.send_json(401, {"error": "Unauthorized"})
            return False
        return True

    def do_POST(self):
        if self.path.split("?", 1)[0] != "/health":
            self.send_json(404, {"error": "Not Found"})
            return
        if not self.request_allowed():
            return
        if self.headers.get("Transfer-Encoding"):
            self.send_json(400, {"error": "Transfer-Encoding is not supported"})
            return
        content_type = self.headers.get("Content-Type", "").lower()
        if not content_type.startswith("application/json"):
            self.send_json(415, {"error": "Content-Type must be application/json"})
            return

        try:
            content_length = int(self.headers.get("Content-Length", ""))
        except ValueError:
            self.send_json(411, {"error": "Content-Length required"})
            return
        if content_length < 0 or content_length > MAX_BODY_BYTES:
            self.send_json(413, {"error": "Request body too large"})
            return
        try:
            body = self.rfile.read(content_length).decode("utf-8")
        except UnicodeDecodeError:
            self.send_json(400, {"error": "Body must be UTF-8"})
            return

        try:
            data = json.loads(body, parse_constant=reject_nonstandard_number)
        except json.JSONDecodeError:
            self.send_json(400, {"error": "Invalid JSON"})
            return
        except PayloadError as exc:
            self.send_json(400, {"error": str(exc)})
            return
        if not isinstance(data, (dict, list)):
            self.send_json(400, {"error": "JSON body must be an object or array"})
            return

        # Store the data
        try:
            counts = store_metrics(data)
            total = sum(counts.values())
            print(f"[{datetime.now().isoformat()}] Stored {total} records: {counts}")

            self.send_json(
                200,
                {
                    "ok": True,
                    "stored": counts,
                },
            )
        except PayloadError as exc:
            self.send_json(400, {"error": str(exc)})
        except Exception as e:
            print(
                f"[{datetime.now().isoformat()}] Error storing data: {e}",
                file=sys.stderr,
            )
            self.send_json(500, {"error": "Unable to store health data"})

    def do_GET(self):
        """Health check endpoint."""
        if self.path.split("?", 1)[0] != "/health":
            self.send_json(404, {"error": "Not Found"})
            return
        if not self.request_allowed():
            return

        # Return basic stats
        try:
            conn = sqlite3.connect(DB_PATH)
            c = conn.cursor()
            c.execute("SELECT COUNT(*) FROM health_metrics")
            metrics = c.fetchone()[0]
            c.execute("SELECT COUNT(*) FROM workouts")
            workouts = c.fetchone()[0]
            c.execute("SELECT COUNT(*) FROM sleep")
            sleep = c.fetchone()[0]
            c.execute("SELECT MAX(received_at) FROM health_metrics")
            last_sync = c.fetchone()[0]
            conn.close()

            self.send_json(
                200,
                {
                    "status": "running",
                    "records": {
                        "metrics": metrics,
                        "workouts": workouts,
                        "sleep": sleep,
                    },
                    "last_sync": last_sync,
                },
            )
        except Exception:
            self.send_json(200, {"status": "running", "db": "not initialized"})

    def log_message(self, format, *args):
        pass  # Quiet logging


if __name__ == "__main__":
    if len(TOKEN.encode("utf-8")) < 32:
        print(
            "ERROR: Health receiver token of at least 32 bytes is required.",
            file=sys.stderr,
        )
        sys.exit(1)
    try:
        for allowed_source in ALLOWED_SOURCES:
            ipaddress.ip_address(allowed_source)
    except ValueError:
        print(
            "ERROR: Health receiver allowed sources must be literal IPs.",
            file=sys.stderr,
        )
        sys.exit(1)
    if (
        not ALLOWED_SOURCES
        or not 1 <= PORT <= 65535
        or RATE_LIMIT < 1
        or RATE_WINDOW_SECONDS < 1
        or not 1 <= MAX_BODY_BYTES <= 67108864
        or MAX_JSON_DEPTH < 1
        or MAX_JSON_NODES < 1
        or MAX_COLLECTION_ITEMS < 1
        or MAX_STRING_BYTES < 1
        or not os.path.isabs(DB_PATH)
    ):
        print("ERROR: Invalid health receiver security limits.", file=sys.stderr)
        sys.exit(1)

    init_db()

    server = HTTPServer((BIND_ADDR, PORT), HealthReceiver)
    print(f"Health Receiver listening on {BIND_ADDR}:{PORT}", file=sys.stderr)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        server.shutdown()
