# =============================================================================
# mercury - Package Configuration
# =============================================================================

packages_host_extra: []
