---
# =============================================================================
# mercury - Kernel Networking
# =============================================================================

sysctl_settings:
  net.ipv4.ip_forward: "1"
