# =============================================================================
# pdm-vm - Backup Configuration
# =============================================================================

restic_backup_paths_extra:
  - /etc/proxmox-datacenter-manager
